- name: 'Copy {{ appd_systemd_service_name }} to {{ appd_systemd_service_path }}'
  template:
    src: '{{ appd_systemd_service_name }}'
    dest: '{{ appd_systemd_service_path }}/{{ appd_systemd_service_name }}'
    owner: root
    group: root
    mode: '0644'

- name: "Make sure service '{{ appd_systemd_service_name }}' is running"
  systemd:
    name: '{{ appd_systemd_service_name }}'
    state: started # started, stopped, restarted
    enabled: true
# https://docs.ansible.com/ansible/latest/modules/systemd_module.html 