- name: "Check if {{ appd_unzip_dir }} exists"
  stat:
    path: "{{ appd_unzip_dir }}"
  register: agent_dir
# https://docs.ansible.com/ansible/latest/modules/stat_module.html

- debug:
    msg: "register {{ agent_dir }}"
# https://docs.ansible.com/ansible/latest/modules/debug_module.html 

- name: "Copy {{ appd_agent_path }} to {{ appd_home_dir }}"
  copy:
    src: "{{ appd_agent_path }}"
    dest: "{{ appd_home_dir }}"  
    owner: appd
    group: appd
    mode: '0644'
# https://docs.ansible.com/ansible/latest/modules/copy_module.html 
# https://chmodcommand.com/ 
  when: not agent_dir.stat.exists

- name: "Create {{ appd_unzip_dir }} if it does not exist"
  file:
    path: '{{ appd_unzip_dir }}'
    recurse: yes
    owner: appd
    group: appd
    mode: '0774'
    state: directory  # directory or file
# https://docs.ansible.com/ansible/latest/modules/file_module.html
# http://www.filepermissions.com/file-permissions-index
  when: not agent_dir.stat.exists

- name: "Extract {{ appd_agent_zip }} into {{ appd_unzip_dir }}"
  unarchive:
    src: '{{ appd_agent_zip }}'
    dest: '{{ appd_unzip_dir }}'
# https://docs.ansible.com/ansible/latest/modules/unarchive_module.html
  when: not agent_dir.stat.exists

- name: "Create symbolic {{ appd_agent_dir }} -> {{ appd_unzip_dir }}"
  file:
    src: '{{ appd_unzip_dir }}'
    dest: '{{ appd_agent_dir }}'
    owner: appd 
    group: appd 
    mode: '0774'
    state: link
# https://docs.ansible.com/ansible/latest/modules/file_module.html
  when: not agent_dir.stat.exists

- name: "Recursively set owner appd and group appd of dir {{ appd_agent_dir }}"
  file:
    path: '{{ appd_agent_dir }}'
    state: directory
    recurse: yes
    owner: appd
    group: appd
    mode: '0774'
  when: not agent_dir.stat.exists

- name: "Delete zip file {{ appd_agent_zip }}"
  file:
    state: absent
    path: "{{ appd_home_dir }}/{{ appd_agent_zip }}"