- name: Login to appdynamics
  uri:
    url: https://identity.msrv.saas.appdynamics.com/v2.0/oauth/token
    method: POST
    body_format: json
    body: '{"username": "{{ download_username }}","password": "{{ download_password }}","scopes": ["download"]}'
    status_code: 200
  register: login
    
- name: "Check if {{ agent_directory }} exists"
  stat:
    path: "{{ agent_directory }}"
  register: stat_machine_agent
    
- name: Download machine agent
  uri:
    url: "{{ download_machine_agent_uri }}"
    method: GET
    headers:
      Authorization: "Bearer {{ login.json.access_token }}"
    dest: "{{ agent_directory }}"
    status_code: 200
  when: not stat_machine_agent.stat.exists